version: '3.8'
services:
    app:
        build: .
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
    db:
        image: mysql:8
        environment:
            MYSQL_DATABASE: shop
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - "3307:3306"
    nginx:
        image: nginx:latest
        ports:
            - "8001:80"
        volumes:
            - ./:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
